# Generated by Django 4.2.16 on 2024-09-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoAppp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
